### ISSUE TITLE
Full activity data available offline?

### ISSUE THREAD

**Issue by yakovsushenok** [malgorzatamaz/react-native-garmin-connect#1]
Hi. Is it possible to pull full activity data with bluetooth/without connecting to internet? Does this library provide an API to retrieve full activity data?

**Comment by malgorzatamaz** [comment]
Hi @yakovsushenok. Library provides way to send data from own Garmin app (via messages) to react native application. If nothing changed since last September, data are send through Garmin cloud services (at least for Android) so it's not possible to do it without connecting to internet. 

Forgive me lack of ReadMe. I'm currently working on making it real library and will add ReadMe in the future.
